# Generated by Django 5.0.4 on 2024-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltitudeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
