# Generated by Django 5.0.4 on 2024-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_altitude', models.BooleanField(default=False)),
                ('message', models.TextField(default='Altitude is A-OK')),
            ],
        ),
    ]
